### ISSUE TITLE
Not able to running the fallowing. 

### ISSUE THREAD

**Issue by mr-j90** [ktbyers/netmiko_tools#36]
Looking for a fix for the following. 

```
 netmiko-show --list-devices
Traceback (most recent call last):
  File "/home/ansible_host/netmiko_tools/netmiko_tools/netmiko-show", line 195, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ansible_host/netmiko_tools/netmiko_tools/netmiko-show", line 102, in main
    display_inventory(my_devices)
  File "/usr/local/lib/python2.7/dist-packages/netmiko/utilities.py", line 97, in display_inventory
    inventory_devices.append((k, v['device_type']))
KeyError: u'device_type'
```

**Comment by ktbyers** [comment]
@y4rden What does your inventory file look (your .netmiko.yml file)? You can obfuscate passwords/other confidential information.

**Comment by mr-j90** [comment]
I was having some issues with the version of Ubuntu 18.04. after moving to 16.04 issue not present.
